name: postbox studios
favicon: null
layout_spectrum: 0.58749
typography_spectrum: 0.59414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#e2e2e2'
    - '#2c2c2c'
    - '#767676'
    - '#b4b4b4'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
