name: postbox studios
favicon: null
layout_spectrum: 0.58749
typography_spectrum: 0.59414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3a1a1'
    - '#a58d8e'
    - '#abc4c4'
    - '#c8b8a3'
    - '#cbd0b9'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
