name: postbox
favicon: null
layout_spectrum: 0.58749
typography_spectrum: 0.59414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3916d'
    - '#1aa3bf'
    - '#1f3468'
    - '#f6ffff'
    - '#000000'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
