name: postbox
favicon: null
layout_spectrum: 0.09431493142619729
typography_spectrum: 0.6516154753044248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9201019450556487
  lightness: 0.9811699413694441
  saturation: 0.9090754855424166
  rhythmicContrast: 0.76223747106269
purpose: []
